#!/usr/bin/python

import sys
import kconfiglib
import menuconfig
import argparse

kconfig = None
try:
    kconfig = kconfiglib.Kconfig("KConfig")
except kconfiglib.KconfigError as e:
    print(e)
    sys.exit(-1)


if __name__ == '__main__':
    menuconfig.menuconfig(kconfig)